name: Deploy App Service (Node 20)

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      db_push:
        description: "Run 'prisma db push' before deploy (first time only, safe for empty DB)"
        required: false
        default: "false"

env:
  NODE_VERSION: "20"
  APP_NAME: "kleppanit-api-prod" # f.eks. kleppanit-api-prod
  PACKAGE_PATH: "release.zip"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install deps (ci)
        run: npm ci

      - name: Build (includes prisma generate)
        run: npm run build

      # Valgfritt: kjør schema til DB første gang (kun tryggt på tom DB)
      - name: Prisma DB Push (optional)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.db_push == 'true' }}
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: npx prisma db push

      - name: Prune dev deps
        run: npm prune --omit=dev

      - name: Create artifact
        run: |
          zip -r ${{ env.PACKAGE_PATH }} \
            dist package.json prisma node_modules

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}
